version: '3'

services:
  payment:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/
      - ./docker/db/tests_bootstrap.sql:/var/scripts/tests_bootstrap.sql
    command: /bin/bash -c "/usr/local/bin/start.sh"
    depends_on:
      - db
      - beanstalkd
    environment:
      DB_HOST: db
      DB_NAME: payment
      DB_TEST_NAME: payment_test
      DB_USER: root
      DB_PASS: root

  db:
    image: mysql:8.0
    volumes:
      - ./docker/db/data:/var/lib/db
      - ./docker/db/migration.sql:/docker-entrypoint-initdb.d/1-migration.sql
      - ./docker/db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./docker/db/tests_bootstrap.sql:/docker-entrypoint-initdb.d/3-test.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment
    ports:
      - "3306:3306"

  beanstalkd:
    image: bodsch/docker-beanstalkd
    ports:
      - "11300:11300"
